# Generated by Django 2.0.2 on 2018-04-10 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='article_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.TextField()),
                ('article_text', models.TextField()),
                ('article_date', models.TextField()),
                ('article_image', models.ImageField(null=True, upload_to='uploads/%Y/%m/%d')),
                ('authorid', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='author.author_data')),
            ],
        ),
        migrations.CreateModel(
            name='category_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
                ('category_description', models.TextField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='article_data',
            name='categoryid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='article.category_data'),
        ),
    ]
