# Generated by Django 2.0.2 on 2018-04-10 04:24

import author.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='author_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_fname', models.TextField()),
                ('author_lname', models.TextField()),
                ('author_email', models.TextField(null=True)),
                ('author_img', models.ImageField(null=True, upload_to=author.models.UploadToPathAndRename('D:\\Vishvesh\\Bony\\Mywebsite\\techwebsite\\media\\user'))),
                ('author_password', models.TextField()),
                ('author_joined', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='otp_generator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('otp', models.CharField(max_length=8)),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author_data')),
            ],
        ),
    ]
